const data = [
  {
    appartmentstatus: "Entire",
    location: "Downtown",
    countryname: "United States",
    cityname: "New York",
    rating: 4.5,
    reviews: 120,
    price: "$759",
    beds: 3,
    imageurl: "/hotel (1).jpg",
    wifi: true,
    date: "01/02/2025",
    countryflagpic: "https://example.com/flags/us-flag.jpg",
  },
  {
    appartmentstatus: "Half",
    location: "Beachfront",
    countryname: "Spain",
    cityname: "Barcelona",
    rating: 4.2,
    reviews: 95,
    price: "$459",
    imageurl: "/hotel (2).jpg",
    beds: 2,
    wifi: true,
    date: "02/25/2024",
    countryflagpic: "https://example.com/flags/es-flag.jpg",
  },
  {
    appartmentstatus: "Entire",
    location: "Historic District",
    countryname: "Italy",
    cityname: "Rome",
    rating: 4.8,
    reviews: 200,
    price: "$599",
    imageurl: "/hotel (3).jpg",
    beds: 4,
    wifi: true,
    date: "02/26/2024",
    countryflagpic: "https://example.com/flags/it-flag.jpg",
  },
  {
    appartmentstatus: "Entire",
    location: "City Center",
    countryname: "France",
    cityname: "Paris",
    rating: 4.7,
    reviews: 150,
    price: "$529",
    imageurl: "/hotel (4).jpg",
    beds: 2,
    wifi: true,
    date: "02/27/2024",
    countryflagpic: "https://example.com/flags/fr-flag.jpg",
  },
  {
    appartmentstatus: "Half",
    location: "Mountain View",
    countryname: "Switzerland",
    cityname: "Zurich",
    rating: 4.9,
    reviews: 180,
    price: "$679",
    imageurl: "/hotel (5).jpg",
    beds: 3,
    wifi: true,
    date: "02/28/2024",
    countryflagpic: "https://example.com/flags/ch-flag.jpg",
  },
];

export default data;
